[profile.default]
src = "src"
out = "out"
libs = ["lib", "../node_modules"]

optimizer = true
optimizer_runs = 1

via_ir = true

fs_permissions = [
    { access = "read-write", path = "./script/benchmark/results" },
    { access = "read", path = "./script/benchmark/BenchmarkConfig.json" },

    { access = "read", path = "../node_modules" },
    { access = "write", path = "../frontend/src/lib/contracts" },
    { access = "write", path = "../frontend/src/lib/deployments" },
]

remappings = [
    "@chainlink/contracts=lib/chainlink-brownie-contracts/contracts/",
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@semaphore-protocol/contracts=../node_modules/@semaphore-protocol/contracts",
    "@zk-kit/lean-imt.sol=../node_modules/@zk-kit/lean-imt.sol",
    "zkvote-lib/=../packages/zkvote-lib/contracts/",
    "@account-abstraction/=lib/account-abstraction/",
]

solc_version = "0.8.28"

[profile.sepolia]
libraries = [
    "poseidon-solidity/PoseidonT3.sol:PoseidonT3:0xB43122Ecb241DD50062641f089876679fd06599a"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
